export const SAMPLE_SHEETS = [
  {
    id: "s1",
    number: "S-001",
    title: "General Notes & Abbreviations",
    type: "Notes",
    status: "Parsed",
  },
  {
    id: "s2",
    number: "S-101",
    title: "Foundation / Anchor Bolt Plan",
    type: "Plan",
    status: "Parsed",
  },
  {
    id: "s3",
    number: "S-102",
    title: "Level 2 Framing Plan",
    type: "Plan",
    status: "Parsed",
  },
  {
    id: "s4",
    number: "S-103",
    title: "Roof Framing Plan",
    type: "Plan",
    status: "Parsed",
  },
  {
    id: "s5",
    number: "S-201",
    title: "North & South Elevations",
    type: "Elevation",
    status: "Parsed",
  },
  {
    id: "s6",
    number: "S-301",
    title: "Typical Details",
    type: "Detail",
    status: "Parsed",
  },
  {
    id: "s7",
    number: "S-401",
    title: "Moment Connection Details",
    type: "Connection",
    status: "Needs Review",
  },
  {
    id: "s8",
    number: "S-501",
    title: "Braced Frame Elevations",
    type: "Elevation",
    status: "Parsed",
  },
];

export const SAMPLE_MEMBER_SUMMARY = [
  { id: "m1", category: "Columns", pieces: 12, tons: 8.4 },
  { id: "m2", category: "Beams & Girders", pieces: 34, tons: 14.7 },
  { id: "m3", category: "HSS Bracing", pieces: 12, tons: 3.6 },
  { id: "m4", category: "Angles / Girts", pieces: 24, tons: 2.4 },
  { id: "m5", category: "Plates & Misc.", pieces: 28, tons: 1.9 },
];

export const SAMPLE_MTO = [
  {
    id: "mto-1",
    mark: "C1",
    category: "Column",
    description: "W12x65 Column",
    size: "W12x65",
    grade: "A992",
    length: 14,
    qty: 8,
    weight: 65,
    unit: "lb/ft",
  },
  {
    id: "mto-2",
    mark: "C2",
    category: "Column",
    description: "W14x82 Column",
    size: "W14x82",
    grade: "A992",
    length: 14,
    qty: 4,
    weight: 82,
    unit: "lb/ft",
  },
  {
    id: "mto-3",
    mark: "B1",
    category: "Beam",
    description: "W16x26 Floor Beam",
    size: "W16x26",
    grade: "A992",
    length: 24.5,
    qty: 18,
    weight: 26,
    unit: "lb/ft",
  },
  {
    id: "mto-4",
    mark: "B2",
    category: "Beam",
    description: "W18x35 Girder",
    size: "W18x35",
    grade: "A992",
    length: 30,
    qty: 10,
    weight: 35,
    unit: "lb/ft",
  },
  {
    id: "mto-5",
    mark: "B3",
    category: "Beam",
    description: "W21x44 Girder",
    size: "W21x44",
    grade: "A992",
    length: 32,
    qty: 6,
    weight: 44,
    unit: "lb/ft",
  },
  {
    id: "mto-6",
    mark: "H1",
    category: "HSS",
    description: "HSS 8x8x3/8 Brace",
    size: "HSS8x8x3/8",
    grade: "A500-B",
    length: 16,
    qty: 12,
    weight: 37.69,
    unit: "lb/ft",
  },
  {
    id: "mto-7",
    mark: "A1",
    category: "Angle",
    description: "L4x4x3/8 Girt",
    size: "L4x4x3/8",
    grade: "A36",
    length: 20,
    qty: 24,
    weight: 9.8,
    unit: "lb/ft",
  },
  {
    id: "mto-8",
    mark: "P1",
    category: "Plate",
    description: "Base Plate 16x16x1",
    size: "PL 1\"",
    grade: "A36",
    length: 1,
    qty: 12,
    weight: 87.2,
    unit: "lb/ea",
  },
  {
    id: "mto-9",
    mark: "P2",
    category: "Plate",
    description: "Cap Plate 12x12x3/4",
    size: "PL 3/4\"",
    grade: "A36",
    length: 1,
    qty: 12,
    weight: 30.6,
    unit: "lb/ea",
  },
  {
    id: "mto-10",
    mark: "M1",
    category: "Misc",
    description: "W8x18 Stair Stringer",
    size: "W8x18",
    grade: "A992",
    length: 18,
    qty: 4,
    weight: 18,
    unit: "lb/ft",
  },
];

export const SAMPLE_CONNECTIONS = {
  typicalShear: 42,
  moment: 8,
  braced: 12,
  basePlates: 12,
  notes:
    "Moment connections at rigid frame grid lines A and D. Typical shear tabs elsewhere. Base plates grouted after plumbing.",
};

export function buildSampleAnalysis(fileCount) {
  return {
    status: "complete",
    progress: 100,
    drawingCount: fileCount || SAMPLE_SHEETS.length,
    sheets: SAMPLE_SHEETS,
    memberSummary: SAMPLE_MEMBER_SUMMARY,
    notes:
      "Detected a two-story steel frame with braced bays on grids 2 and 5. Moment frames along grid lines A and D. Confirm stair scope and any architecturally exposed steel before MTO generation.",
  };
}
